version: "3.8"
networks:
  alsinet:
    external: true
services:
  optimacros:
    build: .
    container_name: optimacros
    image: optimacros
    ports:
      - 443:8080
    networks:
      - alsinet
    volumes:
      - nodejsdata:/usr/src/app/optimacros
    depends_on:
      - ftpd-server

  ftpd-server:
    image: atmoz/sftp
    container_name: sftp
    volumes:
        - ./users.conf:/etc/sftp/users.conf:ro
        - nodejsdata:/home/foo/upload
    ports:
        - "2222:22"

volumes:
  nodejsdata:
    driver: local